;(function () {
    
    var root = this;
    var Module = {};
    var moduleScope = {
        "BigInt": this["BigInt"] || require("./bigint.js"),
    };

(function(){
// -- code generated by emscripten will follow ---
