;(function () {
    var Module = {};
    var root = this;

    if (typeof exports !== 'undefined'){

	    module.exports = Module;
        
    }else{
        root.libotr4Module = Module;
    }

// -- code generated by emscripten will follow ---
